const int rLEDPin=3;
const int bLEDPin=4;
const int gLEDPin=5;
void setup() {
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
}
void loop() {
  digitalWrite(rLEDPin, LOW);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH); 
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, LOW);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, LOW);
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, LOW); 
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, LOW);
  digitalWrite(gLEDPin, LOW);
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, LOW);
  digitalWrite(gLEDPin, HIGH); 
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, LOW);
  digitalWrite(bLEDPin, LOW);
  digitalWrite(gLEDPin, HIGH); 
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
  digitalWrite(rLEDPin, LOW);
  digitalWrite(bLEDPin, LOW);
  digitalWrite(gLEDPin, LOW); 
  delay(500);
  digitalWrite(rLEDPin, HIGH);
  digitalWrite(bLEDPin, HIGH);
  digitalWrite(gLEDPin, HIGH);
  delay(500);
}
